  version: '3.8'

  services:
    docker-dev:
      build: .
      container_name: docker-dev
      hostname: docker-dev
      restart: unless-stopped
      networks:
        dev-macvlan:
          ipv4_address: 192.168.111.15
      volumes:
        - ./workspace:/app
      cap_add:
        - NET_ADMIN

  networks:
    dev-macvlan:
      external: true