#!/bin/bash
#
# Hostname Information and Instructions
# Docker containers get their hostname from docker-compose.yml or Portainer
#

clear
echo "========================================"
echo "  Container Hostname Information"
echo "========================================"
echo ""
echo "Current hostname: $(cat /etc/hostname 2>/dev/null || hostname)"
echo "Actual hostname:  $(hostname)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  You cannot change the hostname from inside a container."
echo ""
echo "The hostname is set by Docker at container creation time."
echo "It comes from the 'hostname:' field in docker-compose.yml"
echo "or the HOSTNAME environment variable in Portainer."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 To change your hostname:"
echo ""
echo "1. In Portainer UI:"
echo "   - Go to: Stacks → your-stack-name → Editor"
echo "   - Find environment variables section"
echo "   - Set: HOSTNAME=your-desired-hostname"
echo "   - Click 'Update the stack'"
echo ""
echo "2. Or edit .env file (if using docker-compose):"
echo "   HOSTNAME=your-desired-hostname"
echo ""
echo "3. Redeploy the container:"
echo "   In Portainer: Pull and redeploy"
echo "   Or: docker-compose down && docker-compose up -d"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Current Configuration:"
echo ""
echo "Expected hostname from build: $(cat /etc/hostname 2>/dev/null || echo 'not set')"
echo "Runtime hostname from Docker: $(hostname)"
echo ""
if [ "$(cat /etc/hostname)" != "$(hostname)" ]; then
    echo "⚠️  MISMATCH DETECTED!"
    echo ""
    echo "The hostname from the Dockerfile (/etc/hostname) doesn't match"
    echo "the runtime hostname set by Docker."
    echo ""
    echo "This happens when:"
    echo "- HOSTNAME environment variable wasn't set in Portainer"
    echo "- docker-compose.yml 'hostname:' field is wrong"
    echo "- Container was created before hostname was configured"
    echo ""
    echo "Solution: Set HOSTNAME in Portainer and redeploy"
fi
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Quick Fix:"
echo ""
echo "In Portainer, add this environment variable:"
echo "   HOSTNAME=my-custom-hostname"
echo ""
echo "Then click: Stacks → your-stack → Pull and redeploy"
echo ""
echo "The new container will have your hostname!"
echo ""
